### ISSUE TITLE
Move core.php

### ISSUE THREAD

**Issue by jmillerdesign** [VolantisDev/CakePHP-Media-Plugin#10]
In the cake-2.0 branch, there is a case issue with the config folder. `config/core.php` should be moved to `Config/core.php`.

**Comment by ReplicaObscura** [comment]
Good point! Submit a pull request if you've got one, otherwise I'll try to get this fixed within the next few days as time permits. Thanks for catching the issue--I could have sworn I already corrected the capitalization of the config directory months ago but apparently didn't :)

**Comment by jmillerdesign** [comment]
Submitted a pull request.
