### ISSUE TITLE
Problem with plugin actions structure

### ISSUE THREAD

**Issue by asmerkin** [VolantisDev/CakePHP-Media-Plugin#12]
Strict (2048): Declaration of TransferBehavior::setup() should be compatible with ModelBehavior::setup(Model $model, $config = Array) [APP/Plugin/Media/Model/Behavior/TransferBehavior.php, line 62]

**Comment by asmerkin** [comment]
include - APP/Plugin/Media/Model/Behavior/TransferBehavior.php, line 62
App::load() - CORE/Cake/Core/App.php, line 558
spl_autoload_call - [internal], line ??
class_exists - [internal], line ??
BehaviorCollection::load() - CORE/Cake/Model/BehaviorCollection.php, line 121
BehaviorCollection::init() - CORE/Cake/Model/BehaviorCollection.php, line 68
Model::__construct() - CORE/Cake/Model/Model.php, line 725
ReflectionClass::newInstance() - [internal], line ??
ClassRegistry::init() - CORE/Cake/Utility/ClassRegistry.php, line 156
Controller::loadModel() - CORE/Cake/Controller/Controller.php, line 734
Controller::__isset() - CORE/Cake/Controller/Controller.php, line 366
Controller::__get() - CORE/Cake/Controller/Controller.php, line 404
AdministratorsController::admin_view() - APP/Controller/AdministratorsController.php, line 73
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 485
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 103
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 85
[main] - APP/webroot/index.php, line 96

**Comment by ReplicaObscura** [comment]
I will check into this one and hopefully have it fixed in my next commit. I'll let you know if I have any further questions about it, otherwise I'll update the ticket once it's resolved.

Thanks!

**Comment by ndm2** [comment]
This is covered by #41
