### ISSUE TITLE
Incorect config file include in shell

### ISSUE THREAD

**Issue by andydhobbs** [VolantisDev/CakePHP-Media-Plugin#14]
In MediaShell.php the config is required() but the file being required is core.php. I believe this should be bootstrap.php?

**Comment by ReplicaObscura** [comment]
You're right, thanks very much for pointing that out. I've been updating Media and getting it set up for a new project of mine and overlooked that when changing core.php to bootstrap.php.

I'll get that fixed in the next commit. Thanks again!

**Comment by AppSynergy** [comment]
README + docs should be updated to reflect this too!

**Comment by ReplicaObscura** [comment]
After briefly looking over the current MediaShell.php code, I don't think this applies any longer (neither core.php nor bootstrap.php are referenced from MediaShell.php currently). Apologies this didn't get resolved earlier, and please do let me know if you still run into an issue with this.
