### ISSUE TITLE
Restructure included 'mm' library

### ISSUE THREAD

**Issue by ReplicaObscura** [VolantisDev/CakePHP-Media-Plugin#16]
I don't want to mess with davidpersson's mm library itself, because it's a separate project that I want to remain compatible with as long as it aligns with my goals. I don't want to have to maintain it, and it seems to work well.

The main problem I have with it, however, is it is in a non-standard package directory (Lib/mm/src/) instead of something more like Lib/MM/. Since underneath the src directory it is using Cake's package naming structure, it still works in Lib, but it just feels a little bit wrong.

Anyway, the main thing that should be changed is the way it's being included throughout the plugin. Previously it was manually including the files wherever they were used, but we should switch to an App::uses call instead since they can be lazy-loaded and potentially show a slight gain if any of the classes are not actually needed.

I had initially tried to implement some App::uses lines which are still in the plugin now, but I didn't fully understand the syntax and how it differed from App::import so I am nearly positive the lines do nothing.

**Comment by ReplicaObscura** [comment]
I'm not sure how much of a consideration this should be. I would still rather see it fit more in line with Cake 2.x naming schemes for Libs, but then again it works as is technically so maybe it would be wasted effort.

**Comment by ndm2** [comment]
As far as I can tell it doesn't fully comply with the CakePHP conventions, as the class names do not match the filenames, ex. `Media_Info` class is in `Info.php`, so lazy loading wouldn't work if I'm not mistaken.

**Comment by ReplicaObscura** [comment]
Good point, I guess a bit more of a restructuring would be required and would probably deviate too much from the original codebase.

**Comment by ndm2** [comment]
Yep, I don't think messing with the library is a good idea. An additional autoloader might do the trick, but I'm not sure if it's worth the hassle. Have you checked whether lazy loading would actually make a noticeable difference regarding performance and/or memory consumption?

**Comment by ndm2** [comment]
Just had a second look at it, and noticed that all the classes that are used by the behaviors/helper are already being included in the plugins bootstrap, so it looks like lazy loading wouldn't make a difference anyways.

**Comment by ReplicaObscura** [comment]
I'd say at this point you've probably thought about this request more than I initially did. I was building some other class libraries with autoloaders for my other Cake plugins when I opened this issue and really liked how they were working, and just wished that this library followed suit, but all in all I don't think it would make a difference to people using the plugin. And since the plugin wraps the library, updating it the way I wanted would probably have no noticeable effect at all.

I'll just close this request as the Media library seems to be working well enough as is. Thanks again for looking further into this!

**Comment by ReplicaObscura** [comment]
And to answer your previous question, I did not go deep enough to investigate whether lazy loading would have a performance or memory impact, it was mainly just an effort to make working on the plugin in the future a little easier, and possibly to avoid loading more classes than needed (though the memory impact of that is probably next to nil).
