### ISSUE TITLE
Missing method listObjects in Cake 2

### ISSUE THREAD

**Issue by asmerkin** [VolantisDev/CakePHP-Media-Plugin#2]
Fatal error: Call to undefined method Configure::listObjects() in PolymorphicBehavior.php on line 78.

**Comment by asmerkin** [comment]
Instead of Configure::listObjects('model'), it should be App:objects('Model');

**Comment by ReplicaObscura** [comment]
Thanks for figuring that one out!

**Comment by ReplicaObscura** [comment]
Should be resolved in latest commit. Thanks again!
