### ISSUE TITLE
Problems with TransferBehavior::checkExtension

### ISSUE THREAD

**Issue by asmerkin** [VolantisDev/CakePHP-Media-Plugin#20]
The current code is: 

//          if (!MediaValidation::extension(${$type}['extension'], $deny, $allow)) {
//              return false;
//          }

But if we use that code, then the extension is double checked and finally the method returns false. It should be: 

```
        if (!MediaValidation::extension(${$type}['basename'], $deny, $allow)) {
            return false;
        }   
```

so pathinfo() inside Validation utility (cakephp core Utility) works Fine. 

Thanks

**Comment by ReplicaObscura** [comment]
Thanks for catching that! I will fix this with my next commit, otherwise feel free to submit a pull request if you'd like it in sooner :)

Thanks again!

Ben

**Comment by ndm2** [comment]
Also covered by #41

**Comment by ReplicaObscura** [comment]
Whew, you beat me to it a year later :) Thanks again @ndm2
