### ISSUE TITLE
Fatal error: 

### ISSUE THREAD

**Issue by lnxg33k** [VolantisDev/CakePHP-Media-Plugin#25]
During the installation steps:
require APP . 'Plugin' . DS . 'Media' . DS . 'Config' . DS . 'core.php';

The Config directory doesn't contain the file named core.php

include - APP/Config/bootstrap.php, line 74
Configure::bootstrap() - CORE/Cake/Core/Configure.php, line 92
require - CORE/Cake/bootstrap.php, line 146
ShellDispatcher::_bootstrap() - CORE/Cake/Console/ShellDispatcher.php, line 131
ShellDispatcher::_initEnvironment() - CORE/Cake/Console/ShellDispatcher.php, line 101
ShellDispatcher::__construct() - CORE/Cake/Console/ShellDispatcher.php, line 57
ShellDispatcher::run() - CORE/Cake/Console/ShellDispatcher.php, line 68
[main] - CORE/Cake/Console/cake.php, line 43</pre></div></pre>PHP Fatal error:  require() [http://php.net/function.require]: Failed opening required '/home/lnxg33k/Desktop/scratch/work/synapse/CTF/Plugin/Media/Config/core.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/lnxg33k/Desktop/scratch/work/synapse/CTF/Config/bootstrap.php on line 74

Fatal error: require() [http://php.net/function.require]: Failed opening required '/home/lnxg33k/Desktop/scratch/work/synapse/CTF/Plugin/Media/Config/core.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/lnxg33k/Desktop/scratch/work/synapse/CTF/Config/bootstrap.php on line 74

**Comment by ReplicaObscura** [comment]
Thanks for the report.

The documentation is out of date based on the recent changes to the plugin--the file now uses bootstrap.php, so you can just specify 'bootstrap' => true when loading Media plugin instead of manually needing to include the config file.

Let me know if you run into further issues. Thanks!

**Comment by ndm2** [comment]
No further response, docs were updated, I'd say this can be closed.
