### ISSUE TITLE
Update installation documentation 

### ISSUE THREAD

**Issue by shawlz** [VolantisDev/CakePHP-Media-Plugin#27]
Installation documentation on step 3 says 

CakePlugin::load('Media');
require APP . 'Plugin' . DS . 'Media' . DS . 'Config' . DS . 'core.php';

instead of 

CakePlugin::load('Media');
require APP . 'Plugin' . DS . 'Media' . DS . 'Config' . DS . 'bootstrap.php';

**Comment by ReplicaObscura** [comment]
Thanks for reporting!

You actually don't need to manually require anything anymore. You can just specify it like this now:

CakePlugin::load('Media', array('bootstrap' => true));

Of course, the same works if you're using CakePlugin::loadAll() as well. I'll get this updated in the documentation as soon as possible. Thanks again!

**Comment by ndm2** [comment]
Docs were updated, so I'd say this can be closed.
