### ISSUE TITLE
Thumbnails not being generated

### ISSUE THREAD

**Issue by ThatGirlSlays** [VolantisDev/CakePHP-Media-Plugin#31]
When I upload an image, only the original is sent to media/transfer/img. No thumbnails are being created.

I downloaded the zip yesterday so I have the most up to date version. I am running 2.2.4 cake. The only lines I changed were the ones I mentioned in the issue about images not displaying in view which were lines 107 and 119 in the plugin bootstrap.php because the images were being uploaded in a folder outside of webroot. I don't think these small changes have anything to do with the thumbnails being generated.

**Comment by ThatGirlSlays** [comment]
P.S. I just reverted back to the original bootstrap file because I had changed the path that files were uploaded to but the issue remains the same. On transfer file is created, no filter or static.

**Comment by AppSynergy** [comment]
I receive an error in GeneratorBehavior.php

``` php
$filter = Configure::read('Media.filter.' . Mime_Type::guessName($file));;
```

(L 159)

should be:

``` php
$filter = Configure::read('Media.filter.default.' . Mime_Type::guessName($file));
```

Based on the config I've got in the latest bootstrap.php:

``` php
Configure::write('Media.filter', array('default' => array(
    'audio' => compact('s', 'm'),
    'document' => compact('s', 'm','original'),
    'generic' => array('original'=>array('clone'=>'copy')),
    'image' => compact('s', 'm', 'l','original'),
    'video' => compact('s', 'm')
)));
```

Now files are created inside /filter.

**Comment by ndm2** [comment]
Again this is pretty old, so I'd say it can be closed until someone can come up with a reproducible problem.

**Comment by ReplicaObscura** [comment]
Agreed. @AppSynergy I'm closing this for now, but please re-open if you still experience this on a current release of the plugin.
