### ISSUE TITLE
Videos not Working

### ISSUE THREAD

**Issue by ThatGirlSlays** [VolantisDev/CakePHP-Media-Plugin#32]
when I try to use the embed or embedAsObject methods of the MediaHelper, nothing is displayed. In fact, when I view the source of my page, it looks like a video embed is never even attempted.

**Comment by ndm2** [comment]
The tests show that it's working fine so far, so again I'd say this can be closed until someone can come up with something reproducible.

**Comment by ReplicaObscura** [comment]
Sounds good to me, thanks @ndm2 for following up on this. @bhndbrwneyes, let us know if you continue to run into any issues with this.
