### ISSUE TITLE
Deleting /releasing images

### ISSUE THREAD

**Issue by designvoid** [VolantisDev/CakePHP-Media-Plugin#36]
I am using the plugin with a hasmany/grouping set up and using the supplied attachments element - adding attachments works fine, no problem at all, however when I try and delete/release an attachment using the checkbox it fails to delete the attachment.

Am I missing something obvious? 

Can I supply any more info to help narrow this down? Happy to try and help fix it!

**Comment by ReplicaObscura** [comment]
I noticed this issue hanging out--sorry it has been sitting there for so long. Are you still experiencing this or have you solved it by now?

**Comment by ReplicaObscura** [comment]
If you do still experience any of these issues, please do re-open or create a new ticket. I'm just cleaning up fo rnow since this was so old.
