### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by smueller91** [VolantisDev/CakePHP-Media-Plugin#37]
I've discovered your plugin right now and steped trough the installation documentation. In the last section under the "Installation" headline you are using the shell command:

chmod 777 -R webroot/media/{transfer,filter}

I'm not sure how it works on windows but on linux you have to enter following to get it work:
chmod -R 777 webroot/media/{transfer,filter}

Nothing special ;)

**Comment by ReplicaObscura** [comment]
Should be all fixed. Thanks!
