### ISSUE TITLE
No uploads in static dir

### ISSUE THREAD

**Issue by deluca687** [VolantisDev/CakePHP-Media-Plugin#38]
Hi,

My uploads are writing to the transfer directory within webroot however are not being moved to the static folder after complete. I've edited bootstrap.php as suggested in issue <a href="https://github.com/bmcclure/CakePHP-Media-Plugin/issues/30#issuecomment-12628803">#30</a> with no luck.  I then reverted to the original bootstrap.php and edited GeneratorBehavior.php as suggested in issue <a href="https://github.com/bmcclure/CakePHP-Media-Plugin/issues/31#issuecomment-14616872">#31</a>, still not getting completed uploads moved from transfer to static directory.  Any suggestions?

**Comment by ndm2** [comment]
The plugin is not ment to work that way, it will not move anything into the `static` folder, it only reads from there. The `static` folders purpose is to hold files required by the application, ie non-user-uploaded files that you want to be able to access using `MediaHelper`.

**Comment by ReplicaObscura** [comment]
@deluca687 I'm closing this for now given the point @ndm2 made about the static directory's purpose. However feel free to re-open if you still feel there is an issue or would like further clarification.
