### ISSUE TITLE
saveAll not working correctly in case validation is involved

### ISSUE THREAD

**Issue by ndm2** [VolantisDev/CakePHP-Media-Plugin#40]
I'm currently in the process of overhauling the whole package. I've stumbeld over #22 and reimplemented the old behavior including 1.3 branch backwards compatibility (need to write some more tests for this), this was what actually made me to do all this, once it was implemented I wanted to write some tests, so I had to fix the test suite, and then one thing lead to another...

I've made everything Cake 2.x, PHP 5.x, PHPUnit and Windows compatible, updated the documenation, adjusted the coding style, fixed some validation, fixed some tests, added some new ones, and much more (I'm going to make it public as soon as I'm done). And while fixing the `Attachment` test I've noticed that `saveAll` isn't quite working, not only because the test itself is incorrect (the files to be transfered are stored under the CakePHP `TMP` folder, but the Attachment model validation doesn't include this path in the location validation), but because of changes in CakePHP regarding saving and validation.

While CakePHP 1.x triggered validation twice, ie it first validated only, and then validated again before the save operation, CakePHP 2.x triggers validation only once. Why is this a problem you may ask? Well, after 2 days of nearly no sleep I figured that the problem is that the Media plugin prepares the files in the `Model::beforeValidate()` callback, stores the preparation results (`TransferBehaviour::_prepare()`) on the model, and reuses these results for the transfer (`TransferBehaviour::transfer()`). 

The problem with this is, that with multiple files that belong to the same model, each file overwrites the result of the previous file in the validation stage, causing the transfer in the saving stage to use the prepared settings of the last file from the validation stage, which leads to multiple files using the same destination, causing version creation to fail. In CakePHP 1.x the additional validation before each save operation triggered the preparation of the file again, causing the correct data to be stored for transer.

So, since I know what the problem is, why don't I fix it? Well, I'm kinda tired, the last two days were pretty stressful, and I have a lot of other work to do too. So while I'm going to fix it later on if no one else does it, I would be very thankful if at least someone could have a look at this, check whether I'm correct and maybe throw in some ideas on what would be the best way to fix this.

It would be pretty easy to force preparation of the file again in `TransferBehaviour::transfer()` (I've tested it, it works), however I'm not sure whether this is a good idea at all.

**Comment by ndm2** [comment]
In case you are interested, for now I've fixed it by forcing a call to `TransferBehaviour::_prepare()`.

https://github.com/ndm2/CakePHP-Media-Plugin/commit/748e130e6b9fc10f6c666aa61b5a096fce98ee48

**Comment by ReplicaObscura** [comment]
Wow, great work so far! This project has been stagnating for a while and really needed this. Thanks for picking it up and making those changes.

**Comment by ndm2** [comment]
Well, I had to do it since I need it in some of my projects, still you're welcome :wink:

Unfortunately the changes are a little mixed up, I wasn't _that_ motivated after I had to redo most of the stuff because my original changes got bricked by the VCS I was previously using, I didn't noticed it and also overwrote my backup with the corrupted data :angry:

Anyways, I have some more on my list (doc updates, console tests, etc...), but the biggest part is done. It will take some time until I can take care of the rest, so I'm going to issue a PR now since it's working fine so far (according to my testing at least), and hopefully others will do some additional testing in the mean time.
