### ISSUE TITLE
MediaHelper should encode URLs

### ISSUE THREAD

**Issue by ndm2** [VolantisDev/CakePHP-Media-Plugin#42]
I think URLs should be percent-encoded by default, and additionally entity-encoded for use in `MediaHelper::embed()` and `MediaHelper::embedAsObject()`.

By default the uploaded files should be realtively safe, the filename is being sent through `Inflector::slug()`, the directory name is retrieved from hard-coded values, the extension however could hold problematic chars (in case possible validation rules allow this), just like the paths supplied to `MediaHelper`, they could contain anything. Non-user uploaded files however should not be expected to be named safely.

So I'd suggest that `MediaHelper::webroot()` and `MediaHelper::url()` should return a percent-encoded URL, and `MediaHelper::embed()` and `MediaHalper::embedAsObject()` should additionally entity-encode them on their own. That way one could still easily use the URLs in a non-HTML context, without having to decode possible entities.

When it comes to percent-encoding we are facing the same "problem" here as the CakePHP core, it's rather complicated to take of the chars `%`, `#` and `?`, see https://github.com/cakephp/cakephp/issues/2238. I think the helper should take the same approach as the Cake core for now, and do not care about `%`, `#` and `?`, but just do basic encoding of the URLs path components.

Any thoughts on this?

**Comment by ReplicaObscura** [comment]
I agree with this. It sounds like a good path to take, at least for now. Assuming that people have control over their paths seems reasonable to me rather than expending a lot of extra effort trying to solve the issue beyond how core is handling it. I'd say if core ever changes the way it handles those characters, Media should probably follow suit.

**Comment by ndm2** [comment]
After further inspection it seems that only the image embedding lacks entity-encoding.
